import type { Icon } from "@phosphor-icons/react";
import {
  HandWaving,
  Barbell,
  PersonSimple,
  Sparkle,
  Leaf,
  ChatCircle,
  Heartbeat,
  Microphone,
  ShieldCheck,
  Headset,
  House,
  MapPin,
  ArrowUpRight,
  ArrowRight,
  Certificate,
  Star,
  Lock,
  Clock,
  CurrencyDollar,
  CheckCircle,
  Plus,
  SlidersHorizontal,
  UserCheck,
  PlusCircle,
  SealCheck,
  ArrowsCounterClockwise,
  Heart,
  HandCoins,
  UsersThree,
  Receipt,
  CalendarCheck,
  ChatCircleDots,
  Briefcase,
  Buildings,
  Phone,
  Armchair,
  Confetti,
  ChartLineUp,
} from "@phosphor-icons/react";

/**
 * Shared Phosphor icon resolver for the redesigned pages (home, pricing,
 * services, how-it-works, about, …). Keyed both by the Lucide names used in
 * `services.json` (so service cards translate cleanly) and by the Phosphor
 * names used directly in content configs. Legacy components keep using the
 * Lucide resolver in `@/lib/icons`.
 */
const PHOSPHOR_ICONS: Record<string, Icon> = {
  // Direct Phosphor names (content-authored).
  ShieldCheck,
  Headset,
  House,
  MapPin,
  ArrowUpRight,
  ArrowRight,
  Certificate,
  Star,
  Lock,
  Clock,
  CurrencyDollar,
  CheckCircle,
  Plus,
  SlidersHorizontal,
  UserCheck,
  PlusCircle,
  SealCheck,
  ArrowsCounterClockwise,
  Heart,
  HandCoins,
  UsersThree,
  Receipt,
  CalendarCheck,
  ChatCircleDots,
  Briefcase,
  Buildings,
  Phone,
  Armchair,
  Confetti,
  ChartLineUp,
  // Lucide service-icon names -> closest Phosphor glyph (matches the mockup).
  HandHelping: HandWaving,
  Dumbbell: Barbell,
  Flower2: PersonSimple,
  Sparkles: Sparkle,
  Salad: Leaf,
  Compass: ChatCircle,
  Activity: Heartbeat,
  MessageCircle: Microphone,
};

export function getPhosphorIcon(name?: string): Icon {
  return (name && PHOSPHOR_ICONS[name]) || Sparkle;
}
