import type {
  AdminBooking,
  AdminService,
  AdminUser,
  Kpi,
  ServicesOverviewItem,
} from "./types";

export const ADMIN_USER: AdminUser = {
  name: "Priya S.",
  role: "Coordinator",
  initials: "PS",
};

export const TODAY_LABEL = "Wednesday, Jun 17, 2024";
export const DASHBOARD_SUBTITLE = "Overview · Today, Jun 17, 2024";

export const KPIS: Kpi[] = [
  { label: "Today's Bookings", value: "12", sub: "↑ 3 from yesterday" },
  {
    label: "Pending Review",
    value: "3",
    sub: "Needs your action",
    tone: "warning",
  },
  { label: "Active Now", value: "7", sub: "In progress" },
  {
    label: "Revenue MTD",
    value: "$4,280",
    sub: "+18% vs last month",
    tone: "success",
  },
];

export const SERVICES_OVERVIEW: ServicesOverviewItem[] = [
  { name: "Beauty", active: 4, pending: 2 },
  { name: "Yoga", active: 3, pending: 1 },
  { name: "Massage", active: 2, pending: 0 },
  { name: "Personal Training", active: 1, pending: 1 },
  { name: "Nutrition", active: 2, pending: 0 },
  { name: "Life Coaching", active: 1, pending: 1 },
];

/**
 * All [Sample] booking rows. Status counts are exact so tab counts stay
 * truthful: 3 pending, 7 active, 12 completed, 2 cancelled (24 total).
 */
export const ALL_BOOKINGS: AdminBooking[] = [
  // --- pending (3) ---
  {
    id: "BK-20240618",
    client: "Sarah M.",
    service: "Yoga · 60 min",
    date: "Jun 20",
    time: "10:00 am",
    total: "$85",
    professional: "Unassigned",
    status: "pending",
  },
  {
    id: "BK-20240617",
    client: "John D.",
    service: "Massage · 90 min",
    date: "Jun 21",
    time: "2:00 pm",
    total: "$120",
    professional: "Unassigned",
    status: "pending",
  },
  {
    id: "BK-20240616",
    client: "Maria L.",
    service: "Personal Training",
    date: "Jun 23",
    time: "8:00 am",
    total: "$95",
    professional: "Unassigned",
    status: "pending",
  },

  // --- active (7) ---
  {
    id: "BK-20240614",
    client: "Sarah C.",
    clientFullName: "Sarah Collins",
    clientEmail: "sarah@email.com",
    service: "Beauty",
    serviceDetail: "Beauty — Hair Styling + Makeup",
    date: "Jun 22",
    time: "9:00 am – 12:00 pm",
    total: "$75+",
    professional: "Aisha T.",
    professionalMatched: true,
    status: "active",
    stage: "Awaiting Pro Confirm",
    priceOverride: "$75 minimum (default)",
    location: "Raleigh, NC (home)",
  },
  {
    id: "BK-20240613",
    client: "James T.",
    service: "Yoga",
    date: "Jun 24",
    total: "$80",
    professional: "Maya R.",
    professionalMatched: true,
    status: "active",
    stage: "Scheduled",
  },
  {
    id: "BK-20240611",
    client: "Tom K.",
    service: "Massage",
    date: "Jun 17",
    total: "$70",
    professional: "David K.",
    professionalMatched: true,
    status: "active",
    stage: "In Progress",
  },
  {
    id: "BK-20240609",
    client: "Nina S.",
    service: "Nutrition",
    date: "Jun 19",
    total: "$90",
    professional: "Lisa M.",
    professionalMatched: true,
    status: "active",
    stage: "Scheduled",
  },
  {
    id: "BK-20240608",
    client: "Carlos R.",
    service: "Life Coaching",
    date: "Jun 20",
    total: "$100",
    professional: "Grace H.",
    professionalMatched: true,
    status: "active",
    stage: "Scheduled",
  },
  {
    id: "BK-20240607",
    client: "Emma W.",
    service: "Beauty",
    date: "Jun 21",
    total: "$75",
    professional: "Aisha T.",
    professionalMatched: true,
    status: "active",
    stage: "Awaiting Pro Confirm",
  },
  {
    id: "BK-20240606",
    client: "Daniel P.",
    service: "Personal Training",
    date: "Jun 22",
    total: "$90",
    professional: "Marcus L.",
    professionalMatched: true,
    status: "active",
    stage: "Scheduled",
  },

  // --- completed (12) ---
  {
    id: "BK-20240612",
    client: "Tom K.",
    service: "Yoga",
    date: "Jun 15",
    total: "$85",
    professional: "Maya R.",
    status: "completed",
  },
  {
    id: "BK-20240610",
    client: "Lisa R.",
    service: "Massage",
    date: "Jun 14",
    total: "$110",
    professional: "David K.",
    status: "completed",
  },
  {
    id: "BK-20240605",
    client: "Olivia B.",
    service: "Beauty",
    date: "Jun 13",
    total: "$95",
    professional: "Aisha T.",
    status: "completed",
  },
  {
    id: "BK-20240604",
    client: "Noah G.",
    service: "Personal Training",
    date: "Jun 12",
    total: "$90",
    professional: "Marcus L.",
    status: "completed",
  },
  {
    id: "BK-20240603",
    client: "Ava M.",
    service: "Nutrition",
    date: "Jun 11",
    total: "$85",
    professional: "Lisa M.",
    status: "completed",
  },
  {
    id: "BK-20240602",
    client: "Liam F.",
    service: "Life Coaching",
    date: "Jun 10",
    total: "$100",
    professional: "Grace H.",
    status: "completed",
  },
  {
    id: "BK-20240601",
    client: "Sophia K.",
    service: "Yoga",
    date: "Jun 9",
    total: "$80",
    professional: "Maya R.",
    status: "completed",
  },
  {
    id: "BK-20240531",
    client: "Mason D.",
    service: "Massage",
    date: "Jun 8",
    total: "$115",
    professional: "David K.",
    status: "completed",
  },
  {
    id: "BK-20240530",
    client: "Isabella T.",
    service: "Beauty",
    date: "Jun 7",
    total: "$120",
    professional: "Aisha T.",
    status: "completed",
  },
  {
    id: "BK-20240529",
    client: "Ethan R.",
    service: "Personal Training",
    date: "Jun 6",
    total: "$90",
    professional: "Marcus L.",
    status: "completed",
  },
  {
    id: "BK-20240528",
    client: "Mia C.",
    service: "Nutrition",
    date: "Jun 5",
    total: "$85",
    professional: "Lisa M.",
    status: "completed",
  },
  {
    id: "BK-20240527",
    client: "Lucas H.",
    service: "Yoga",
    date: "Jun 4",
    total: "$80",
    professional: "Maya R.",
    status: "completed",
  },

  // --- cancelled (2) ---
  {
    id: "BK-20240526",
    client: "Grace W.",
    service: "Massage",
    date: "Jun 3",
    total: "$110",
    professional: "Unassigned",
    status: "cancelled",
  },
  {
    id: "BK-20240525",
    client: "Henry J.",
    service: "Beauty",
    date: "Jun 2",
    total: "$95",
    professional: "Unassigned",
    status: "cancelled",
  },
];

export const PENDING_BOOKINGS: AdminBooking[] = ALL_BOOKINGS.filter(
  (b) => b.status === "pending",
);
export const ACTIVE_BOOKINGS: AdminBooking[] = ALL_BOOKINGS.filter(
  (b) => b.status === "active",
);

export const ADMIN_SERVICES: AdminService[] = [
  {
    id: "yoga-private-session",
    name: "Yoga — Private Session",
    category: "Wellness",
    basePrice: "$80",
    duration: "60 min",
    status: "active",
  },
  {
    id: "yoga-group-up-to-4",
    name: "Yoga — Group (up to 4)",
    category: "Wellness",
    basePrice: "$65/person",
    duration: "60 min",
    status: "active",
  },
  {
    id: "beauty-hair-styling",
    name: "Beauty — Hair Styling",
    category: "Beauty",
    basePrice: "From $75",
    maxPrice: "$180",
    duration: "60–120 min",
    status: "active",
    description:
      "Professional hair styling services performed in your home. Includes blowout, styling, and finishing.",
    availability: { weekdays: true, weekends: true, sameDay: false },
  },
  {
    id: "beauty-makeup-application",
    name: "Beauty — Makeup Application",
    category: "Beauty",
    basePrice: "From $75",
    duration: "45–90 min",
    status: "active",
  },
  {
    id: "massage-swedish",
    name: "Massage — Swedish",
    category: "Massage",
    basePrice: "$95",
    duration: "60 min",
    status: "active",
  },
  {
    id: "massage-deep-tissue",
    name: "Massage — Deep Tissue",
    category: "Massage",
    basePrice: "$115",
    duration: "90 min",
    status: "active",
  },
  {
    id: "personal-training",
    name: "Personal Training",
    category: "Fitness",
    basePrice: "$90",
    duration: "60 min",
    status: "active",
  },
  {
    id: "nutrition-coaching",
    name: "Nutrition Coaching",
    category: "Wellness",
    basePrice: "$85",
    duration: "50 min",
    status: "inactive",
  },
  {
    id: "life-coaching",
    name: "Life Coaching",
    category: "Wellness",
    basePrice: "$100",
    duration: "60 min",
    status: "active",
  },
  {
    id: "physical-therapy",
    name: "Physical Therapy",
    category: "Medical",
    basePrice: "$110",
    duration: "60 min",
    status: "inactive",
  },
];
